### ISSUE TITLE
[Feature request] Custom CSS rules support

### ISSUE THREAD

**Issue by Azumgi** [readium/readium-desktop#222]
Currently, one can use Readium with only 1 predefined style (1.5 if considering light/dark themes support). Which means there are almost no customizations.

Adding a simple textbox (or just a separate css file) where user can define custom stylesheet for the book view (like in Calibre) would give a full control over how everything looks: from basic things like a background picture, to some advanced stuff, like using different rules for different window resolutions. 

This is very powerful feature that shouldn't come at a great cost, since Readium is an electron-based app and the basic implementation is just loading external css file.

Just an example of my desktop Calibre setup, which almost completely overrides default theme:

![image](https://user-images.githubusercontent.com/35058624/54695199-94507d00-4b3a-11e9-92db-9dce53fef29e.png)

```css
@font-face {
  font-family: MyFonts;
  unicode-range: U+4E00-9FFF, U+3400-4DFF, U+FF00-FFEF, U+3000-303F;
  src: url("file:///C:/Programs/Calibre2/resources/my_style/FangSong.ttf");
}

@font-face {
  font-family: MyFonts;
  font-style: normal;
  text-align: justify;
  font-weight: normal;
  src: url("file:///C:/Programs/Calibre2/resources/my_style/CharterITC_Normal.otf");
}

@font-face {
  font-family: MyFonts;
  font-style: italic;
  text-align: justify;
  font-weight: normal;
  src: url("file:///C:/Programs/Calibre2/resources/my_style/CharterITC_Italic.otf");
}

@font-face {
  font-family: MyFonts;
  font-style: normal;
  font-weight: bold;
  src: url("file:///C:/Programs/Calibre2/resources/my_style/CharterITC_Bold.otf");
}

@font-face {
  font-family: MyFonts;
  font-weight: bold;
  font-style: italic;
  src: url("file:///C:/Programs/Calibre2/resources/my_style/CharterITC_Bold_Italic.otf");
}

body {
  background: url("file:///C:/Programs/Calibre2/resources/my_style/old_paper.png") top left no-repeat !important;
  background-attachment: fixed !important;
  font-family: MyFonts !important;
}

::selection {
  background: rgba(255, 172, 71, .6) !important;
}

h1, h2, h3, h4, h5, h6 {
  background-color: transparent !important;
  border: transparent !important;
  color: black !important;
  text-align: center !important;
  font-weight: bold !important;
}

a {
  color: rgb(50, 50, 170) !important;
}

p, .paragraph {
  text-indent: 80px !important;
  line-height: 1.5 !important;
  font-size: 23px !important;
  line-height: 27px !important;
  margin-top: 0.8em !important;
  margin-bottom: 0.8em !important;

  -webkit-font-smoothing: antialiased !important;
  text-rendering: optimizeSpeed !important;
  font-family: MyFonts !important;
  color: black !important;
}

ol, ul {
  -webkit-margin-before: 0.8em !important;
  -webkit-margin-after: 0.8em !important;
  -webkit-margin-start: 0px !important;
  -webkit-margin-end: 0px !important;
  -webkit-padding-start: 80px !important;
}

span {
  color: black !important;
}

h1 {
  font-size: 48px !important;
}

h2 {
  font-size: 44px !important;
}

h3 {
  font-size: 40px !important;
}

h4 {
  font-size: 38px !important;
}

h5 {
  font-size: 34px !important;
}

h6 {
  font-size: 32px !important;
}
```
